version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - mkdir $CODEBUILD_SRC_DIR/build
      - mv $CODEBUILD_SRC_DIR/build/* $CODEBUILD_SRC_DIR/build/  #mueve toda la carpeta que se crea build a la carpeta build en el pipeline

artifacts:
  files: '**/*'
