version: 0.2

phases:
  install:
    commands:
      - npm install
      

  build:
    commands:
      - npm run build
      - aws s3 sync build s3://cinecolombia-contenido/ --delete
      - aws s3 sync build s3://cinecolombia-contenido/ 

artifacts:
  files: '**/*'
